# Generated by Django 5.1.3 on 2025-03-21 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('a_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('a_email', models.CharField(max_length=254, unique=True)),
                ('a_name', models.CharField(max_length=100, unique=True)),
                ('a_password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='ALogTable',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(blank=True, null=True)),
                ('login', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, null=True)),
                ('minor_job_id', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('import_file', models.TextField(blank=True, null=True)),
                ('import_timestamp', models.DateTimeField(blank=True, null=True)),
                ('export_file', models.TextField(blank=True, null=True)),
                ('export_timestamp', models.DateTimeField(blank=True, null=True)),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('log_duration', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'a_log_table',
            },
        ),
        migrations.CreateModel(
            name='CorpusTable',
            fields=[
                ('language_profeciency', models.CharField(max_length=255)),
                ('corpus_id', models.TextField(primary_key=True, serialize=False)),
                ('target_lang', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'corpus_table',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'custom_django_session',
            },
        ),
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_file_name', models.CharField()),
                ('generated_file_name', models.CharField()),
                ('language_proficiency', models.CharField()),
                ('import_date', models.DateTimeField()),
                ('status', models.CharField()),
            ],
            options={
                'db_table': 'file_import',
            },
        ),
        migrations.CreateModel(
            name='JobTable',
            fields=[
                ('sen_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('source_data', models.CharField(max_length=255)),
                ('t_target_data', models.CharField(blank=True, max_length=255, null=True)),
                ('r_target_data', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_id', models.IntegerField()),
                ('minor_job_id', models.IntegerField(blank=True, null=True)),
                ('major_job_id', models.IntegerField()),
                ('t_flag', models.CharField(max_length=1)),
                ('r_flag', models.CharField(max_length=1)),
                ('corpus_id', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('t_assigned', models.CharField(max_length=1)),
                ('r_assigned', models.CharField(max_length=1)),
                ('t_rating', models.IntegerField(blank=True, null=True)),
                ('t_reviews', models.CharField(blank=True, max_length=255, null=True)),
                ('r_reviews', models.CharField(blank=True, max_length=255, null=True)),
                ('file_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_table',
            },
        ),
        migrations.CreateModel(
            name='MajorTable',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField()),
            ],
            options={
                'db_table': 'major_table',
            },
        ),
        migrations.CreateModel(
            name='RegistrationTable',
            fields=[
                ('id', models.CharField(blank=True, null=True)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=50)),
                ('language_profeciency', models.TextField()),
                ('org_details', models.BinaryField(blank=True, null=True)),
                ('flag', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'registration_table',
            },
        ),
        migrations.CreateModel(
            name='ReviewerTable',
            fields=[
                ('r_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('r_name', models.CharField()),
                ('password', models.CharField()),
                ('email', models.CharField()),
                ('language_profeciency', models.CharField()),
                ('major_job_id', models.IntegerField(blank=True, null=True)),
                ('minor_job_id', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('batch_range', models.CharField(blank=True, null=True)),
                ('corpus_id', models.TextField(blank=True, null=True)),
                ('job_assigned', models.CharField(max_length=1)),
                ('completed_batches', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviewer_table',
            },
        ),
        migrations.CreateModel(
            name='TLogTable',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('t_id', models.CharField(blank=True, null=True)),
                ('batch_range', models.CharField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('login', models.DateTimeField(blank=True, null=True)),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('log_duration', models.DateTimeField(blank=True, null=True)),
                ('module_access_timestamp', models.DateTimeField(blank=True, null=True)),
                ('module_submission_timestamp', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_log_table',
            },
        ),
        migrations.CreateModel(
            name='TranslatorTable',
            fields=[
                ('t_id', models.CharField(primary_key=True, serialize=False)),
                ('t_name', models.CharField()),
                ('password', models.CharField()),
                ('email', models.CharField()),
                ('language_profeciency', models.CharField()),
                ('major_job_id', models.IntegerField(blank=True, null=True)),
                ('minor_job_id', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('batch_range', models.CharField(blank=True, null=True)),
                ('t_review', models.CharField(blank=True, null=True)),
                ('corpus_id', models.TextField(blank=True)),
                ('job_assigned', models.CharField(max_length=1)),
                ('completed_batches', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'translator_table',
            },
        ),
        migrations.CreateModel(
            name='RLogTable',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('batch_range', models.CharField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('login', models.DateTimeField(blank=True, null=True)),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('log_duration', models.DateTimeField(blank=True, null=True)),
                ('module_access_timestamp', models.DateTimeField(blank=True, null=True)),
                ('module_submission_timestamp', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('r', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='translation_app.reviewertable')),
            ],
            options={
                'db_table': 'r_log_table',
            },
        ),
    ]
