# Generated by Django 5.1.3 on 2025-03-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewertable',
            name='file_assigned',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewertable',
            name='quit_flag',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewertable',
            name='quit_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='translatortable',
            name='file_assigned',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatortable',
            name='quit_flag',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatortable',
            name='quit_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobtable',
            name='sen_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewertable',
            name='r_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
