# Generated by Django 5.1.3 on 2025-03-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_app', '0002_reviewertable_file_assigned_reviewertable_quit_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpustable',
            name='target_lang',
        ),
        migrations.AddField(
            model_name='corpustable',
            name='keyboard_filename',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corpustable',
            name='keyboard_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corpustable',
            name='keyboard_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corpustable',
            name='language_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corpustable',
            name='language_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
